//! EIP-712 voucher signing and verification.
//!
//! Vouchers use EIP-712 typed data signing with the domain:
//! - name: "Tempo Stream Channel"
//! - version: "1"
//! - chainId: from configuration
//! - verifyingContract: escrow contract address
//!
//! The voucher struct contains:
//! - `channelId`: bytes32 channel identifier
//! - `cumulativeAmount`: uint128 cumulative payment amount

use alloy::primitives::{Address, Bytes, FixedBytes, Signature, U256};
use alloy::signers::Signer;
use alloy::sol_types::{Eip712Domain, SolStruct};

use super::types::{SignedVoucher, Voucher as VoucherType};

/// EIP-712 type definition for the Voucher struct.
///
/// Generated by alloy's sol! macro. The struct name "Voucher" is significant —
/// it determines the EIP-712 type hash and must match the TypeScript reference.
mod eip712 {
    alloy::sol! {
        struct Voucher {
            bytes32 channelId;
            uint128 cumulativeAmount;
        }
    }
}

/// Build the EIP-712 domain separator for stream vouchers.
///
/// Domain parameters match the TypeScript reference:
/// `{ name: "Tempo Stream Channel", version: "1", chainId, verifyingContract }`
pub fn voucher_domain(chain_id: u64, verifying_contract: Address) -> Eip712Domain {
    Eip712Domain {
        name: Some("Tempo Stream Channel".into()),
        version: Some("1".into()),
        chain_id: Some(U256::from(chain_id)),
        verifying_contract: Some(verifying_contract),
        salt: None,
    }
}

/// Sign a voucher using EIP-712 typed data signing.
///
/// Returns a [`SignedVoucher`] with a 65-byte signature (r + s + v).
pub async fn sign_voucher<S: Signer + Send + Sync>(
    signer: &S,
    voucher: &VoucherType,
    chain_id: u64,
    verifying_contract: Address,
) -> Result<SignedVoucher, crate::error::MppError> {
    let domain = voucher_domain(chain_id, verifying_contract);
    let sol_voucher = eip712::Voucher {
        channelId: voucher.channel_id,
        cumulativeAmount: voucher.cumulative_amount,
    };

    let hash = sol_voucher.eip712_signing_hash(&domain);
    let signature = signer
        .sign_hash(&hash)
        .await
        .map_err(|e| crate::error::MppError::Http(format!("Failed to sign voucher: {e}")))?;

    Ok(SignedVoucher {
        channel_id: voucher.channel_id,
        cumulative_amount: voucher.cumulative_amount,
        signature: Bytes::from(signature.as_bytes().to_vec()),
    })
}

/// Verify a voucher signature and recover the signer address.
///
/// Supports both Ethereum-standard (v=27/28) and raw (v=0/1) parity formats.
pub fn verify_voucher(
    signed: &SignedVoucher,
    chain_id: u64,
    verifying_contract: Address,
) -> Result<Address, crate::error::MppError> {
    let domain = voucher_domain(chain_id, verifying_contract);
    let sol_voucher = eip712::Voucher {
        channelId: signed.channel_id,
        cumulativeAmount: signed.cumulative_amount,
    };

    let hash = sol_voucher.eip712_signing_hash(&domain);
    let sig_bytes = signed.signature.as_ref();
    if sig_bytes.len() != 65 {
        return Err(crate::error::MppError::InvalidPayload(Some(format!(
            "Invalid signature length: expected 65, got {}",
            sig_bytes.len()
        ))));
    }

    // Parse 65-byte signature: r (32) + s (32) + v (1)
    let v = sig_bytes[64];
    let parity = match v {
        0 | 27 => false,
        1 | 28 => true,
        _ => {
            return Err(crate::error::MppError::InvalidPayload(Some(format!(
                "Invalid signature v value: {v}"
            ))));
        }
    };

    let sig = Signature::from_bytes_and_parity(&sig_bytes[..64], parity);
    let recovered = sig
        .recover_address_from_prehash(&hash)
        .map_err(|e| crate::error::MppError::Http(format!("Failed to recover signer: {e}")))?;

    Ok(recovered)
}

/// Parse a signed voucher from credential payload string fields.
///
/// Converts string-encoded fields (from the JSON credential payload)
/// into a typed [`SignedVoucher`].
pub fn parse_voucher_from_payload(
    channel_id: &str,
    cumulative_amount: &str,
    signature: &str,
) -> Result<SignedVoucher, crate::error::MppError> {
    let channel_id: FixedBytes<32> = channel_id.parse().map_err(|e| {
        crate::error::MppError::InvalidPayload(Some(format!("Invalid channel_id: {e}")))
    })?;

    let cumulative_amount: u128 = cumulative_amount.parse().map_err(|e| {
        crate::error::MppError::InvalidPayload(Some(format!("Invalid cumulative_amount: {e}")))
    })?;

    let sig_bytes: Bytes = signature.parse().map_err(|e| {
        crate::error::MppError::InvalidPayload(Some(format!("Invalid signature: {e}")))
    })?;

    Ok(SignedVoucher {
        channel_id,
        cumulative_amount,
        signature: sig_bytes,
    })
}

#[cfg(test)]
mod tests {
    use super::*;
    use alloy_signer_local::PrivateKeySigner;

    fn test_escrow_address() -> Address {
        "0x1234567890abcdef1234567890abcdef12345678"
            .parse()
            .unwrap()
    }

    fn test_channel_id() -> FixedBytes<32> {
        FixedBytes::from([
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 1,
        ])
    }

    #[tokio::test]
    async fn test_sign_and_verify_round_trip() {
        let signer = PrivateKeySigner::random();
        let expected_address = signer.address();
        let chain_id = 42431u64;
        let escrow = test_escrow_address();

        let voucher = VoucherType {
            channel_id: test_channel_id(),
            cumulative_amount: 5_000_000,
        };

        let signed = sign_voucher(&signer, &voucher, chain_id, escrow)
            .await
            .unwrap();

        assert_eq!(signed.channel_id, test_channel_id());
        assert_eq!(signed.cumulative_amount, 5_000_000);
        assert_eq!(signed.signature.len(), 65);

        let recovered = verify_voucher(&signed, chain_id, escrow).unwrap();
        assert_eq!(recovered, expected_address);
    }

    #[tokio::test]
    async fn test_verify_wrong_signer() {
        let signer = PrivateKeySigner::random();
        let other_signer = PrivateKeySigner::random();
        let chain_id = 42431u64;
        let escrow = test_escrow_address();

        let voucher = VoucherType {
            channel_id: test_channel_id(),
            cumulative_amount: 5_000_000,
        };

        let signed = sign_voucher(&signer, &voucher, chain_id, escrow)
            .await
            .unwrap();

        let recovered = verify_voucher(&signed, chain_id, escrow).unwrap();
        assert_ne!(recovered, other_signer.address());
    }

    #[tokio::test]
    async fn test_verify_tampered_amount() {
        let signer = PrivateKeySigner::random();
        let expected_address = signer.address();
        let chain_id = 42431u64;
        let escrow = test_escrow_address();

        let voucher = VoucherType {
            channel_id: test_channel_id(),
            cumulative_amount: 5_000_000,
        };

        let mut signed = sign_voucher(&signer, &voucher, chain_id, escrow)
            .await
            .unwrap();

        // Tamper with the cumulative amount
        signed.cumulative_amount = 10_000_000;

        // Recovered address should NOT match the original signer
        let recovered = verify_voucher(&signed, chain_id, escrow).unwrap();
        assert_ne!(recovered, expected_address);
    }

    #[tokio::test]
    async fn test_verify_wrong_chain_id() {
        let signer = PrivateKeySigner::random();
        let expected_address = signer.address();
        let escrow = test_escrow_address();

        let voucher = VoucherType {
            channel_id: test_channel_id(),
            cumulative_amount: 5_000_000,
        };

        let signed = sign_voucher(&signer, &voucher, 42431, escrow)
            .await
            .unwrap();

        // Verify with wrong chain ID — recovered address should differ
        let recovered = verify_voucher(&signed, 4217, escrow).unwrap();
        assert_ne!(recovered, expected_address);
    }

    #[test]
    fn test_verify_invalid_signature_length() {
        let signed = SignedVoucher {
            channel_id: test_channel_id(),
            cumulative_amount: 5_000_000,
            signature: Bytes::from(vec![0u8; 32]),
        };

        let result = verify_voucher(&signed, 42431, test_escrow_address());
        assert!(result.is_err());
        let err = result.unwrap_err();
        assert!(err.to_string().contains("signature length"));
    }

    #[test]
    fn test_parse_voucher_from_payload() {
        let channel_id = "0x0000000000000000000000000000000000000000000000000000000000000001";
        let cumulative_amount = "5000000";
        // 65 zero bytes as hex
        let signature = format!("0x{}", "00".repeat(65));

        let result = parse_voucher_from_payload(channel_id, cumulative_amount, &signature).unwrap();
        assert_eq!(result.channel_id, test_channel_id());
        assert_eq!(result.cumulative_amount, 5_000_000);
        assert_eq!(result.signature.len(), 65);
    }

    #[test]
    fn test_parse_voucher_invalid_amount() {
        let result = parse_voucher_from_payload(
            "0x0000000000000000000000000000000000000000000000000000000000000001",
            "not_a_number",
            &format!("0x{}", "00".repeat(65)),
        );
        assert!(result.is_err());
        assert!(result
            .unwrap_err()
            .to_string()
            .contains("cumulative_amount"));
    }

    #[test]
    fn test_parse_voucher_invalid_channel_id() {
        let result =
            parse_voucher_from_payload("not_a_hex", "5000000", &format!("0x{}", "00".repeat(65)));
        assert!(result.is_err());
        assert!(result.unwrap_err().to_string().contains("channel_id"));
    }

    #[test]
    fn test_voucher_domain_fields() {
        let domain = voucher_domain(42431, test_escrow_address());
        assert_eq!(domain.name, Some("Tempo Stream Channel".into()));
        assert_eq!(domain.version, Some("1".into()));
        assert_eq!(domain.chain_id, Some(U256::from(42431)));
        assert_eq!(domain.verifying_contract, Some(test_escrow_address()));
        assert_eq!(domain.salt, None);
    }
}
