name: Release
on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Changelogs
        uses: wevm/changelogs-rs@master
        with:
          conventional-commit: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
