name: Scan GitHub Actions

on:
  pull_request:
    paths:
      - ".github/**"
  push:
    branches:
      - main
    paths:
      - ".github/**"
  workflow_dispatch:
  schedule:
    - cron: "19 7 * * 1"

permissions: {}

jobs:
  scan:
    name: Scan GitHub Actions
    uses: tempoxyz/gh-actions/.github/workflows/scan-github-actions.yml@891834ec16535af9d8b7f30ce157967243f8ac24
    permissions:
      id-token: write
      actions: read
      contents: read
